config/routes.rb
Rails.application.routes.draw do
  root to: 'cats#index'
  get '/scores', to: 'scores#index'
  patch '/scores', to: 'scores#update'
  resources :cats, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  validates :auid, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all.sample(2)
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController

  def index
    @cats = Cat.order(score: :desc)
  end

  def update
    UpdateScoresService.new(permited_hash).call
    redirect_to root_path
  end

  private

  def permited_hash
    permited_params.to_h.symbolize_keys
  end

  def permited_params
    params.permit(:cats_id, :selected_cat_id)
  end
end

app/views/cats/index.html.erb
<div class="container" style="margin-bottom: 20px;">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <h3 class="text-center"> CatMash </h3>
    </div>
  </div>
  <div class="row">
    <% @cats.each do |cat| %>
      <%= form_tag("/scores", method: "patch") do %>
        <div class="col-xs-6">
          <div class="avatar-container">
            <div class="avatar" style="background-image: url(<%= cat.url %>);">
            </div>
          </div>
          <h5 class="text-center"> Score : <%= cat.score %> </h5>
          <%= hidden_field_tag(:cats_id, "#{@cats[0].id} #{@cats[1].id}")  %>
          <%= hidden_field_tag(:selected_cat_id, cat.id)  %> 
          <div class="text-center">
            <%= submit_tag("Vote !", class: "btn btn-primary")%>
          </div>
        </div>
 
      <% end %>
    <% end %>

  </div>
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <%= link_to scores_path do %>
        <h4 class="text-center"> Ranking </h4>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CatMash</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/scores/index.html.erb
<div class=container style="margin-bottom: 20px;">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <%= link_to root_path do %>
        <h4 class="text-center" id="link-home"> Back to vote </h4>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <ol>
        <% @cats.each do |cat| %>
          <li>
            <h5 class="text-center"> Score : <%= cat.score %> </h5>
            <div class="avatar" style="background-image: url(<%= cat.url %>);">
            </div>
          </li>
        <% end %>
      </ol>
    </div>
  </div>
</div>